import type { SupabaseClient } from '@supabase/supabase-js';
import { createHash, randomUUID } from 'node:crypto';
import { test, expect, login, synced } from './fixture';
import { RouteDrain } from './route-drain';
const course='film-handwriting-v1';
const syntheticSheet=Buffer.from('UklGRqYDAABXRUJQVlA4IJoDAACwIACdASrIABgBPm02mUmkIyKhIPVYEIANiWlu/HyZyOtOC9sj+q+BvgQ8aH1v5L+V+KT1gWSD+6Y7v/I/aB56n6B+QHkv9A38o/0XnB3g0xj+df437nfe5/sf7R+Tns4+Vf+z/bPgD/k388/1v9U/un/l+AD1Yfrt7E/68f/8EHzp06dOm+h1oXS63MjhBKIQZvU56GcMgXymxShOgN3RsakymShOtLrxe2zsvVTJoHNPqsOvJV5p7FnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06dOnTp06b4AA/v/ZND56csGJlE4TxKLV/yj6DszDgB1sp0lr4POKTBo9UH9QLdcdxLR6/U2fYbH/G8/DKZNdpDRwr3auNF263FHz/DhzbpFaLC//GwZZ58ligf9aLPpzGExowuOQcCd5LuuPaticoawIQv1A9znWZrP4Ps5Ip9ak0ii9OtIJ8M4V/2nM7z6TR9Fxe/SkGPpzSbcR+CwUUxJbKt5fZsVOWqoOY1mg/4JO+KxJwcoHg1v3AoxUf/MYz/gg9oNAf4zB6yh1biAdiA+QAduhkNsswIKYqAs/Nk8AaV5N3tvAE+yspUpN1Jtj5J2CRf9JegyavGQcPx6BFis10/fnqm/h1rY63LMwcbIdn1DYpurVnvxLFbwxCQ7yWN2no5oq+MbV49Y5SHpOzKk2aagJwoJf/4SjH//6dioCylE3kLC3489wjC/48WoChJ7rKAsUDa7aezgICLvhrJAI5EFmNuRjfp6Hw8gmt3MQWe/y0uiGZvubouy7Fye8HdGxicYXX7KNzMfcUlnLQYZhuMXx8HF4ie7yQrS7gocddbNzwc3FnE/8Qe5sPFAGRXePIRP98nHJ7mkD9hQajJ4MnTpwVAPiFCkKHyDBkPjGw2sul52VMUQPvTSmTkdxJtbBIZvYnAj8qbIhXf5aEmRzSB5p2vyU6XQv/zGLSn6N+N/Ryuxrsz8+FjKScIXN5SsPwu03Mp+OLLAXxGMNf/9Mx2uQVF8vBreB2G4O7Rsj77+t3oEWw7HPv44539tL8mMw5Br7PC+0LzXqzsuCYxqR1fbPP6Iw+hINTYsFzes8WRwjFTL2pEZ6j/rlYmXgtuG6Ir6s9sa5NvjZDH/rIXJ9x9j+tlOoSLo4AAAAAAAAAAAA','base64');
async function seedMaterials(qa: { account: { id: string; client: SupabaseClient } }) {
 const root=`${qa.account.id}/learning/film-v1`;
 for(const [name,body,mime] of [['ready.txt',Buffer.from('yeoni-private-handwriting-v1'),'text/plain'],['workbook.pdf',Buffer.from('%PDF-1.4 synthetic QA only'),'application/pdf'],...['02','03','04'].map(n=>[`page-${n}.webp`,syntheticSheet,'image/webp'])] as [string,Buffer,string][]) expect((await qa.account.client.storage.from('growth-resources').upload(`${root}/${name}`,body,{contentType:mime})).error).toBeNull();
}


test('handwriting paper course saves once, resumes old progress and isolates owners at 320px',async({page,qa})=>{
 await qa.account.client.from('growth_routines').insert({id:randomUUID(),user_id:qa.account.id,category:'handwriting',title:'검증 손글씨',target_minutes:15,enabled:true});
 await qa.account.client.from('growth_sessions').insert({user_id:qa.account.id,session_date:'2020-01-01',status:'completed',source:'handwriting',metrics:{courseId:course,lessonId:'film-p2',lessonCompleted:true}});
 await seedMaterials(qa);await page.setViewportSize({width:320,height:844});await login(page,qa.account);await synced(page);const before=await qa.read();await page.goto('/growth/handwriting');
 await expect(page.getByRole('region',{name:'손글씨 학습 진도'})).toContainText('1 / 53 수업 완료');await expect(page.getByRole('heading',{name:'2강 · 기본 모음',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'이 수업 완료하고 저장'})).toBeDisabled();await page.getByLabel('긴 획과 짧은 획의 비율을 살폈어요.').check();await page.getByLabel('글자 크기를 일정하게 맞춰 봤어요.').check();await page.getByLabel('실제로 연습한 시간 (분)').fill('12');
 const pattern='**/rest/v1/growth_sessions*',drain=new RouteDrain();let posts=0;await page.route(pattern,route=>drain.run(async()=>{if(route.request().method()==='POST'){posts++;await route.fetch();await route.fulfill({status:503,contentType:'application/json',body:'{"message":"lost"}'});}else await route.fallback();}));
 try{await page.getByRole('button',{name:'이 수업 완료하고 저장'}).click();await expect(page.getByRole('button',{name:'수업 저장 완료',exact:true})).toBeDisabled();expect(posts).toBe(1);}finally{await drain.wait();await page.unroute(pattern);}
 const rows=await qa.account.client.from('growth_sessions').select('*');expect(rows.data).toHaveLength(2);expect(rows.data!.find(row=>row.session_date!=='2020-01-01')).toMatchObject({actual_minutes:12,metrics:{courseId:course,lessonId:'film-p3',mode:'paper',timeSource:'self-reported'}});
 await page.reload();await expect(page.getByRole('heading',{name:'3강 · 복합 모음',exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'손글씨 학습 진도'})).toContainText('2 / 53 수업 완료');
 const pdf=await page.request.get('/learning/handwriting/film-v1/workbook.pdf');expect(pdf.status()).toBe(404);const mine=await qa.account.client.storage.from('growth-resources').download(`${qa.account.id}/learning/film-v1/workbook.pdf`);expect(mine.error).toBeNull();const publicUrl=qa.account.client.storage.from('growth-resources').getPublicUrl(`${qa.account.id}/learning/film-v1/workbook.pdf`).data.publicUrl;expect((await page.request.get(publicUrl)).status()).not.toBe(200);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const other=await qa.createAccount();expect((await other.client.from('growth_sessions').select('*')).data).toEqual([]);expect((await other.client.storage.from('growth-resources').download(`${qa.account.id}/learning/film-v1/workbook.pdf`)).error).not.toBeNull();expect(await qa.read()).toEqual(before);
});

test('handwriting screen worksheet draws, undoes and saves a private lesson image',async({page,qa})=>{
 await qa.account.client.from('growth_routines').insert({id:randomUUID(),user_id:qa.account.id,category:'handwriting',title:'검증 손글씨',target_minutes:15,enabled:true});
 await seedMaterials(qa);await login(page,qa.account);await synced(page);await page.goto('/growth/handwriting');await expect(page.getByRole('region',{name:'손글씨 학습 진도'})).toContainText('0 / 53 수업 완료');await expect(page.getByRole('img',{name:/필림 유인물/})).toBeVisible();await page.getByRole('button',{name:'이 화면에 직접 쓰기',exact:true}).click();await expect(page.getByText('연습지 준비 중…')).toHaveCount(0);
 const canvas=page.getByLabel('수업 손글씨 연습장');await expect(canvas).toBeVisible();const box=(await canvas.boundingBox())!;
 for(let i=0;i<2;i++){await page.mouse.move(box.x+30,box.y+50+i*20);await page.mouse.down();await page.mouse.move(box.x+130,box.y+70+i*20,{steps:5});await page.mouse.up();}
 await expect(page.getByText(/직접 쓴 획 2개/)).toBeVisible();await page.getByRole('button',{name:'되돌리기',exact:true}).click();await expect(page.getByText(/직접 쓴 획 1개/)).toBeVisible();await page.getByLabel('어깨와 손에 힘을 빼고 그렸어요.').check();await page.getByLabel('선 사이의 간격을 비교했어요.').check();await page.getByRole('button',{name:'이 수업 완료하고 저장'}).click();await expect(page.getByRole('button',{name:'수업 저장 완료',exact:true})).toBeDisabled();
 const session=(await qa.account.client.from('growth_sessions').select('*').single()).data!;expect(session.metrics).toMatchObject({courseId:course,lessonId:'film-p2',strokes:1,mode:'screen'});const resource=(await qa.account.client.from('growth_resources').select('*').single()).data!;expect(session.metrics.resourceId).toBe(resource.id);expect((await qa.account.client.storage.from('growth-resources').download(resource.storage_path)).error).toBeNull();const other=await qa.createAccount();expect((await other.client.storage.from('growth-resources').download(resource.storage_path)).error).not.toBeNull();await page.getByRole('button',{name:'다음 미완료 수업'}).click();await expect(page.getByRole('heading',{name:'2강 · 기본 모음',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'2강 · 기본 모음',exact:true})).toBeVisible();
});

test('handwriting progress failure is explicit and retry recovers without writes',async({page,qa})=>{
 await login(page,qa.account);await synced(page);const pattern='**/rest/v1/growth_sessions*';await page.route(pattern,async route=>{if(route.request().url().includes('metrics=cs.'))await route.fulfill({status:503,contentType:'application/json',body:'{"message":"unavailable"}'});else await route.fallback();});await page.goto('/growth/handwriting');await expect(page.getByText('수업 진도를 불러오지 못했어요. 다시 불러온 뒤 이어서 연습해 주세요.')).toBeVisible();await expect(page.getByRole('button',{name:'이 수업 완료하고 저장'})).toBeDisabled();await page.unroute(pattern);await page.getByRole('button',{name:'진도 다시 불러오기'}).click();await expect(page.getByRole('region',{name:'손글씨 학습 진도'})).toContainText('0 / 53 수업 완료');expect((await qa.account.client.from('growth_sessions').select('*')).data).toEqual([]);
});

 test('handwriting private package registers only in the signed-in owner folder',async({page,qa})=>{
 await login(page,qa.account);await synced(page);await page.goto('/growth/handwriting');await expect(page.getByRole('region',{name:'비공개 손글씨 교재'})).toContainText('등록된 비공개 교재를 확인하지 못했어요.');
 const files=['workbook.pdf',...Array.from({length:53},(_,i)=>`page-${String(i+2).padStart(2,'0')}.webp`)].map(name=>{const bytes=name==='workbook.pdf'?Buffer.from('%PDF-1.4 QA'):syntheticSheet;return {name,mimeType:name==='workbook.pdf'?'application/pdf':'image/webp',base64:bytes.toString('base64'),sha256:createHash('sha256').update(bytes).digest('hex')};});
 await page.getByText('처음 한 번 교재 등록',{exact:true}).click();await page.getByLabel('교재 묶음 파일').setInputFiles({name:'qa-materials.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'yeoni-private-handwriting-v1',files}))});
 await expect(page.getByRole('region',{name:'비공개 손글씨 교재'})).toContainText('교재를 내 계정에 비공개로 등록했어요.',{timeout:60000});await expect(page.getByRole('img',{name:/필림 유인물/})).toBeVisible();
 const root=`${qa.account.id}/learning/film-v1`;expect((await qa.account.client.storage.from('growth-resources').list(root,{limit:100})).data).toHaveLength(55);const other=await qa.createAccount();expect((await other.client.storage.from('growth-resources').download(`${root}/page-02.webp`)).error).not.toBeNull();await page.reload();await expect(page.getByRole('img',{name:/필림 유인물/})).toBeVisible();
 });
