'use client';

import { useEffect, useState } from 'react';
import { COMMON_INTENSITY, DayWorkout, SAFETY_STOP_MESSAGE } from '../data/workouts';
import { FOAM_ROLLER_AFTER_ROUTINE, FOAM_ROLLER_AREA_GUIDES, FOAM_ROLLER_AREAS, FOAM_ROLLER_BEFORE_ROUTINE, FOAM_ROLLER_DISC_WARNING, FOAM_ROLLER_FORBIDDEN, FOAM_ROLLER_INTRO, FOAM_ROLLER_RECOVERY_ROUTINE, FOAM_ROLLER_TIMING_LABELS, FoamRollerTiming } from '../data/foamRoller';
import { RECOVERY_REASON_LABELS, RECOVERY_ROUTINE, RECOVERY_STOP_CRITERIA, RecoveryDayRecord } from '../data/recoveryMode';
import FlowDiagram from './FlowDiagram';
import PhaseSection from './PhaseSection';

interface DayViewProps { day: DayWorkout; isCompleted: boolean; onSaveWorkout: (pain: boolean, memo: string) => void; onCancelWorkout: () => void; workoutPain?: boolean; workoutMemo?: string; cardioDone?: boolean; cardioType?: string; cardioMinutes?: number; cardioMemo?: string; onSaveCardio?: (type: string, minutes: number, memo: string) => void; onCancelCardio?: () => void; foamRollerDone?: boolean; foamRollerTiming?: FoamRollerTiming; foamRollerAreas?: string[]; foamRollerPain?: boolean; foamRollerMemo?: string; onSaveFoamRoller?: (record: { foamRollerTiming?: FoamRollerTiming; foamRollerAreas?: string[]; foamRollerPain?: boolean; foamRollerMemo?: string }) => void; onCancelFoamRoller?: () => void; onPullupTraining?: () => void; recovery?: RecoveryDayRecord; onRecordRecovery?: (memo: string) => void; onCancelRecovery?: () => void; showBaseRoutine?: boolean; onShowRecommended?: () => void; onShowBaseRoutine?: () => void }

export default function DayView({ day, isCompleted, onSaveWorkout, onCancelWorkout, workoutPain = false, workoutMemo = '', cardioDone = false, cardioType = '슬라이딩보드', cardioMinutes = 15, cardioMemo = '', onSaveCardio, onCancelCardio, foamRollerDone = false, foamRollerTiming = 'before', foamRollerAreas = [], foamRollerPain = false, foamRollerMemo = '', onSaveFoamRoller, onCancelFoamRoller, onPullupTraining, recovery, onRecordRecovery, onCancelRecovery, showBaseRoutine = true, onShowRecommended, onShowBaseRoutine }: DayViewProps) {
  const [warning, setWarning] = useState(false);
  const [pain, setPain] = useState(workoutPain);
  const [memo, setMemo] = useState(workoutMemo);
  const [recoveryMemo, setRecoveryMemo] = useState(recovery?.recoveryMemo || '');
  const [selectedCardioType, setSelectedCardioType] = useState(cardioType || '슬라이딩보드');
  const [selectedCardioMinutes, setSelectedCardioMinutes] = useState(cardioMinutes || 15);
  const [cardioMemoDraft, setCardioMemoDraft] = useState(cardioMemo || '');
  const [selectedFoamTiming, setSelectedFoamTiming] = useState<FoamRollerTiming>(foamRollerTiming || 'before');
  const [selectedFoamAreas, setSelectedFoamAreas] = useState<string[]>(foamRollerAreas || []);
  const [foamPain, setFoamPain] = useState(foamRollerPain);
  const [foamMemoDraft, setFoamMemoDraft] = useState(foamRollerMemo || '');
  useEffect(() => { setPain(workoutPain); setMemo(workoutMemo); }, [workoutPain, workoutMemo]);
  useEffect(() => { setRecoveryMemo(recovery?.recoveryMemo || ''); }, [recovery?.recoveryMemo]);
  useEffect(() => { setSelectedCardioType(cardioType || '슬라이딩보드'); setSelectedCardioMinutes(cardioMinutes || 15); setCardioMemoDraft(cardioMemo || ''); }, [cardioType, cardioMinutes, cardioMemo]);
  useEffect(() => { setSelectedFoamTiming(foamRollerTiming || 'before'); setSelectedFoamAreas(foamRollerAreas || []); setFoamPain(foamRollerPain); setFoamMemoDraft(foamRollerMemo || ''); }, [foamRollerTiming, foamRollerAreas, foamRollerPain, foamRollerMemo]);
  const exercises = day.phases.flatMap((p) => p.exercises).filter((e) => e.sets !== 0 || e.intervalPlan || e.abSlideGate);
  const highRiskNames = ['슬라이딩보드', '고블릿 스쿼트', '매달리기', '런지', '무리한 코어 운동'];
  const isRecoveryRecommended = Boolean(recovery?.recoveryMode);
  const isCardioDay = day.id === 'sat';
  const cardioTypes = ['슬라이딩보드', '실내 걷기', '야외 걷기', '고정식 자전거', '가벼운 계단 오르기', '제자리 걷기', '스트레칭 + 가벼운 움직임', '기타'];
  const cardioMinuteOptions = [10, 15, 20];
  const toggleFoamArea = (area: string) => setSelectedFoamAreas((prev) => prev.includes(area) ? prev.filter((item) => item !== area) : [...prev, area]);
  const reasonLabels = recovery?.reasons.map((reason) => RECOVERY_REASON_LABELS[reason]).filter(Boolean) || [];
  return <div>
    {recovery && <section className={`mb-4 rounded-2xl border p-4 shadow-sm ${isRecoveryRecommended ? 'border-amber-200 bg-amber-50 text-amber-900' : 'border-green-100 bg-green-50 text-green-800'}`}>
      <div className="flex items-start justify-between gap-3"><div><p className="text-[12px] font-semibold">오늘 상태</p><h2 className="mt-1 text-[18px] font-bold">{isRecoveryRecommended ? '회복 운동 권장' : '일반 운동'}</h2></div><span className="rounded-full bg-white px-3 py-1 text-[12px] font-bold">권장 강도: {recovery.intensity === '70%' ? '70%' : recovery.intensity === 'recovery' ? '회복' : '정상'}</span></div>
      {isRecoveryRecommended ? <div className="mt-3 rounded-xl bg-white/75 p-3 text-[13px] leading-relaxed"><p className="font-bold">오늘은 회복 운동 권장일입니다.</p><p>강한 운동 대신 폼롤러 5~10분과 가벼운 호흡을 추천합니다.<br />허리 아래쪽은 직접 굴리지 말고, 엉덩이와 허벅지 위주로 진행하세요.</p><p className="mt-2 font-bold">회복 우선일은 운동을 실패한 것이 아니라 몸을 회복하는 날입니다.</p></div> : <p className="mt-3 text-[13px]">일반식 기반 기본 루틴을 진행해도 됩니다. 통증·저림·어지럼이 있으면 즉시 중단하세요.</p>}
      <p className="mt-3 text-[12px]"><b>원인:</b> {reasonLabels.length ? reasonLabels.join(' / ') : '특이사항 없음'}</p>
      <label className="mt-3 block text-[12px] font-bold text-gray-700">회복 메모<textarea value={recoveryMemo} onChange={(e) => setRecoveryMemo(e.target.value)} placeholder="상태 입력" className="mt-2 min-h-20 w-full rounded-xl border border-amber-100 px-3 py-2 text-[13px] font-normal" /></label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5"><button onClick={onShowRecommended} className="rounded-xl bg-[#534AB7] px-2 py-2 text-[12px] font-bold text-white">오늘 추천 루틴</button><button onClick={onShowBaseRoutine} className="rounded-xl bg-white px-2 py-2 text-[12px] font-bold text-gray-700">기존 루틴 보기</button><button onClick={() => onRecordRecovery?.(recoveryMemo)} className="rounded-xl bg-green-600 px-2 py-2 text-[12px] font-bold text-white">회복 우선으로 기록</button><button onClick={onCancelRecovery} className="rounded-xl bg-red-50 px-2 py-2 text-[12px] font-bold text-red-600 sm:col-span-2">회복 기록 취소</button></div>
      {recovery.completedAsRecovery && <p className="mt-2 rounded-xl bg-white/80 px-3 py-2 text-[12px] font-bold text-green-700">회복 운동 완료/회복 우선으로 기록됨</p>}
    </section>}
    {isRecoveryRecommended && !showBaseRoutine && <section className="mb-4 rounded-2xl border border-green-100 bg-white p-4 shadow-sm"><p className="text-[16px] font-bold text-gray-900">회복 운동 루틴 · 20~25분</p><div className="mt-3 space-y-2">{RECOVERY_ROUTINE.map((item, idx) => <div key={item} className="rounded-xl bg-green-50 px-3 py-2 text-[13px] text-green-800">{idx + 1}) {item}</div>)}</div><p className="mt-3 text-[12px] font-bold text-red-700">중단 기준: {RECOVERY_STOP_CRITERIA.join(' · ')}</p></section>}
    {(!isRecoveryRecommended || showBaseRoutine) && <><div className="flex justify-between items-start mb-4"><div><p className="text-[17px] font-medium text-gray-800">{day.title}</p><p className="text-[12px] text-gray-400 mt-0.5">{day.subtitle}</p></div><span className="text-white text-[11px] font-medium px-3 py-1 rounded-full shrink-0 ml-2" style={{ background: day.badgeBg }}>{day.totalTime}</span></div>
    <button type="button" onClick={() => setWarning(true)} className="w-full mb-3 py-3 px-4 rounded-xl text-[14px] font-bold bg-[#FCEBEB] text-[#A32D2D] border border-red-200">통증·저림·어지러움 발생</button>
    {warning && <div className="mb-4 rounded-2xl bg-[#FCEBEB] border-2 border-[#E24B4A] p-4 text-[#791F1F]"><p className="text-[18px] font-bold mb-1">운동을 즉시 중단하세요.</p><p className="text-[13px] leading-relaxed">허리 통증, 다리 저림, 날카로운 무릎 통증 또는 어지러움이 지속되면 무리하지 말고 의료진과 상담하세요.</p><button className="mt-3 text-[12px] underline" onClick={() => setWarning(false)}>안내 접기</button></div>}
    <div className="mb-4 rounded-xl bg-white border border-gray-100 p-3"><p className="text-[13px] font-semibold text-gray-800 mb-2">저장되는 운동: {day.title}</p><div className="flex gap-1.5 overflow-x-auto">{exercises.map((e, i) => <span key={`${e.name}-${i}`} className="shrink-0 rounded-full bg-[#EEEDFE] text-[#3C3489] px-2.5 py-1 text-[11px]">{i + 1}. {e.name}</span>)}</div></div>
    <div className="mb-4 grid gap-1.5 rounded-xl bg-[#E6F1FB] p-3 text-[12px] text-[#0C447C]"><p className="font-semibold">운동 강도 기준</p>{COMMON_INTENSITY.map((x) => <p key={x}>• {x}</p>)}<p>• 최근 약 3개월 정도 운동을 쉬었기 때문에 처음 2주는 2세트 기준으로 진행합니다.</p><p>• 덤벨 고블릿 스쿼트는 5~7kg부터 시작하고, 자세가 무너지면 무게를 낮춥니다.</p><p>• 덤벨과 밴드 운동은 가벼운 강도로 다시 시작합니다.</p><p>• AB 슬라이더는 처음 1~2주차에는 준비 자세만 진행하고, 허리 통증이나 다리 저림이 있으면 즉시 제외합니다.</p><p>• 묵주기도 슬라이딩보드는 기도를 이어갈 수 있을 정도의 저강도로 진행합니다.</p><p className="font-semibold text-[#A32D2D]">{SAFETY_STOP_MESSAGE} 중단은 실패가 아니라 회복일 전환입니다.</p></div>

    <section className="mb-4 rounded-2xl border border-emerald-100 bg-white p-4 shadow-sm">
      <p className="text-[12px] font-bold text-emerald-700">폼롤러 사용법 안내</p>
      <h3 className="mt-1 text-lg font-bold text-gray-900">준비운동/회복 장비</h3>
      <p className="mt-2 rounded-xl bg-emerald-50 px-3 py-2 text-[13px] font-semibold text-emerald-800">{FOAM_ROLLER_INTRO}</p>
      <p className="mt-2 rounded-xl bg-red-50 px-3 py-2 text-[12px] font-bold text-red-700">{FOAM_ROLLER_DISC_WARNING}</p>
      <div className="mt-3 grid gap-2 sm:grid-cols-3">
        <div className="rounded-xl bg-gray-50 p-3"><p className="font-bold text-[13px]">운동 전 폼롤러 3분</p>{FOAM_ROLLER_BEFORE_ROUTINE.map((item) => <p key={item} className="mt-1 text-[12px] text-gray-600">- {item}</p>)}</div>
        <div className="rounded-xl bg-gray-50 p-3"><p className="font-bold text-[13px]">운동 후 폼롤러 5분</p>{FOAM_ROLLER_AFTER_ROUTINE.map((item) => <p key={item} className="mt-1 text-[12px] text-gray-600">- {item}</p>)}</div>
        <div className="rounded-xl bg-gray-50 p-3"><p className="font-bold text-[13px]">회복 우선일 루틴</p>{FOAM_ROLLER_RECOVERY_ROUTINE.map((item) => <p key={item} className="mt-1 text-[12px] text-gray-600">- {item}</p>)}</div>
      </div>
      <details className="mt-3 rounded-xl bg-gray-50 p-3 text-[12px] text-gray-600"><summary className="cursor-pointer font-bold text-gray-800">부위별 사용법과 금지 사용법 보기</summary><div className="mt-2 space-y-2">{FOAM_ROLLER_AREA_GUIDES.map((item) => <p key={item.area}><b>{item.area}</b>: {item.guide}</p>)}<div className="rounded-lg bg-red-50 p-2 font-semibold text-red-700">{FOAM_ROLLER_FORBIDDEN.map((item) => <p key={item}>• {item}</p>)}</div></div></details>
    </section>
    {onSaveFoamRoller && <section className="mb-4 rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm"><p className="text-[12px] font-bold text-emerald-700">폼롤러 기록</p><h3 className="mt-1 text-lg font-bold text-gray-900">{foamRollerDone ? '폼롤러 기록됨' : '폼롤러 완료 저장'}</h3><p className="mt-2 text-[13px] font-bold text-gray-700">진행 시점</p><div className="mt-2 flex flex-wrap gap-2">{(Object.keys(FOAM_ROLLER_TIMING_LABELS) as FoamRollerTiming[]).map((timing) => <button key={timing} type="button" onClick={() => setSelectedFoamTiming(timing)} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${selectedFoamTiming === timing ? 'bg-emerald-600 text-white' : 'bg-gray-50 text-gray-600'}`}>{FOAM_ROLLER_TIMING_LABELS[timing]}</button>)}</div><p className="mt-3 text-[13px] font-bold text-gray-700">진행 부위</p><div className="mt-2 flex flex-wrap gap-2">{FOAM_ROLLER_AREAS.map((area) => <button key={area} type="button" onClick={() => toggleFoamArea(area)} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${selectedFoamAreas.includes(area) ? 'bg-emerald-600 text-white' : 'bg-gray-50 text-gray-600'}`}>{area}</button>)}</div><label className="mt-3 flex items-center gap-2 rounded-xl bg-gray-50 px-3 py-2 text-[13px] font-semibold text-gray-700"><input type="checkbox" checked={foamPain} onChange={(e) => setFoamPain(e.target.checked)} className="h-4 w-4 accent-[#E24B4A]" />통증 또는 불편감 있음</label><label className="mt-3 block text-[13px] font-bold text-gray-700">메모<textarea value={foamMemoDraft} onChange={(e) => setFoamMemoDraft(e.target.value)} placeholder="폼롤러 느낌 입력" className="mt-2 min-h-20 w-full rounded-xl border border-gray-200 px-3 py-2 text-[13px] font-normal" /></label><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => onSaveFoamRoller({ foamRollerTiming: selectedFoamTiming, foamRollerAreas: selectedFoamAreas, foamRollerPain: foamPain, foamRollerMemo: foamMemoDraft })} className="rounded-xl bg-emerald-600 px-4 py-3 text-[14px] font-bold text-white">폼롤러 완료로 기록</button><button type="button" onClick={onCancelFoamRoller} className="rounded-xl bg-red-50 px-4 py-3 text-[14px] font-bold text-red-600">폼롤러 기록 취소</button></div></section>}
    {onPullupTraining && ['mon', 'sat'].includes(day.id) && <button type="button" onClick={onPullupTraining} className="w-full mb-3 py-3 px-4 rounded-xl text-[14px] font-bold bg-[#EEEDFE] text-[#3C3489] border border-[#AFA9EC]">철봉 단계 훈련 진행</button>}
    <section className="mb-4 rounded-2xl border border-[#D9D6FF] bg-white p-4 shadow-sm"><p className="text-[12px] font-bold text-[#534AB7]">오늘 운동 기록</p><h3 className="mt-1 text-lg font-bold text-gray-900">{isCompleted ? '오늘 운동 기록됨' : '오늘 운동 완료 저장'}</h3><p className="mt-2 text-[13px] font-semibold text-gray-700">오늘 루틴: {day.title}</p><div className="mt-3 rounded-xl border border-gray-100 bg-gray-50 p-3 text-[13px] text-gray-700"><p className="font-bold text-gray-800">기록될 운동:</p>{exercises.map((e) => <p key={`record-${e.name}`} className="mt-1">- {e.name}</p>)}</div><label className="mt-3 flex items-center gap-2 rounded-xl bg-gray-50 px-3 py-2 text-[13px] font-semibold text-gray-700"><input type="checkbox" checked={pain} onChange={(e) => setPain(e.target.checked)} className="h-4 w-4 accent-[#E24B4A]" />통증 있음</label><label className="mt-3 block text-[13px] font-bold text-gray-700">메모<textarea value={memo} onChange={(e) => setMemo(e.target.value)} placeholder="운동 느낌 입력" className="mt-2 min-h-20 w-full rounded-xl border border-gray-200 px-3 py-2 text-[13px] font-normal" /></label><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => onSaveWorkout(pain, memo)} className="rounded-xl bg-[#534AB7] px-4 py-3 text-[14px] font-bold text-white">{isCompleted ? '수정 저장' : '오늘 운동 완료로 기록'}</button><button type="button" onClick={onCancelWorkout} className="rounded-xl bg-red-50 px-4 py-3 text-[14px] font-bold text-red-600">운동 기록 취소</button></div></section>

    {isCardioDay && onSaveCardio && <section className="mb-4 rounded-2xl border border-[#9CCAF0] bg-white p-4 shadow-sm"><p className="text-[12px] font-bold text-[#185FA5]">오늘 유산소 기록</p><h3 className="mt-1 text-lg font-bold text-gray-900">{cardioDone ? '유산소 기록됨' : '유산소 완료 저장'}</h3><p className="mt-2 text-[12px] text-gray-500">추천 우선순위: 슬라이딩보드 → 실내/야외 걷기 → 고정식 자전거 → 기타 가벼운 유산소</p><p className="mt-3 text-[13px] font-bold text-gray-700">유산소 종류</p><div className="mt-2 flex flex-wrap gap-2">{cardioTypes.map((type) => <button key={type} type="button" onClick={() => setSelectedCardioType(type)} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${selectedCardioType === type ? 'bg-[#378ADD] text-white' : 'bg-gray-50 text-gray-600'}`}>{type}</button>)}</div><p className="mt-3 text-[13px] font-bold text-gray-700">운동 시간</p><div className="mt-2 flex flex-wrap gap-2">{cardioMinuteOptions.map((minutes) => <button key={minutes} type="button" onClick={() => setSelectedCardioMinutes(minutes)} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${selectedCardioMinutes === minutes ? 'bg-[#378ADD] text-white' : 'bg-gray-50 text-gray-600'}`}>{minutes}분</button>)}<label className="flex items-center gap-1 rounded-full bg-gray-50 px-3 py-1.5 text-[12px] font-bold text-gray-600">직접 입력<input type="number" min={1} value={selectedCardioMinutes} onChange={(e) => setSelectedCardioMinutes(Number(e.target.value) || 0)} className="w-14 rounded border border-gray-200 px-1 py-0.5 text-right" />분</label></div><label className="mt-3 block text-[13px] font-bold text-gray-700">메모<textarea value={cardioMemoDraft} onChange={(e) => setCardioMemoDraft(e.target.value)} placeholder="운동 느낌 입력" className="mt-2 min-h-20 w-full rounded-xl border border-gray-200 px-3 py-2 text-[13px] font-normal" /></label><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => onSaveCardio(selectedCardioType, selectedCardioMinutes, cardioMemoDraft)} className="rounded-xl bg-[#378ADD] px-4 py-3 text-[14px] font-bold text-white">유산소 완료로 기록</button><button type="button" onClick={onCancelCardio} className="rounded-xl bg-red-50 px-4 py-3 text-[14px] font-bold text-red-600">유산소 기록 취소</button></div></section>}
    <FlowDiagram flow={day.flow} />
    {day.phases.map((phase, i) => {
      const offset = day.phases.slice(0, i).reduce((sum, p) => sum + p.exercises.length, 0);
      return <PhaseSection key={i} phase={phase} exercises={day.phases.flatMap((p) => p.exercises)} offset={offset} highRiskNames={isRecoveryRecommended ? highRiskNames : []} />;
    })}
    </>}
  </div>;
}
