import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {parsePack,newDocument,parseAttempt,type Attempt,type Stroke} from './model.ts';
import {originalState,originalFrames,originalSnapshot,originalCandidates,originalEligible,PALETTES} from './original.ts';
import {originalLines} from './original-guide.ts';
import {recommend,confirmedStage} from './recommend.ts';
const p=parsePack(JSON.parse(readFileSync(new URL('../../content/drawing/foundations-v1.json',import.meta.url),'utf8'))),owner=crypto.randomUUID();
const ink=(color='#34314b'):Stroke=>({points:[[100,100,.5],[210,230,.5]],color,width:2.6,erase:false});
function make(n:number,sources:Attempt[]=[],motif=0):Attempt{const l=p.lessons[n-1],a:Attempt={id:crypto.randomUUID(),user_id:owner,revision:1,status:'completed',created_at:'2026-09-25',updated_at:'2026-09-25',document:newDocument(l,l.examples[motif],p.version)};a.document.original={...originalState(a),compared:true,sources:sources.map(originalSnapshot)};const s=a.document.original;if(sources.length){s.projectId=sources[0].document.original!.projectId;s.design=structuredClone(sources[0].document.original!.design);}a.document.references=s.sources.map(x=>x.attemptId);a.document.character={name:'새봄',role:'앱 친구',personality:'다정함',features:'잎과 몸',improvement:'팔 방향'};a.document.strokes=[ink()];a.document.step=4;a.document.check='independent';return a;}
function chain(){const a=make(71),b=make(72,[a]);b.document.original!.panels.round=[ink()];b.document.original!.panels.tall=[ink()];b.document.original!.reason='포근해 보여요';const c=make(73,[b]),base=make(74,[c]);return {a,b,c,base};}
test('all 80 lessons playable; all D71–D80 have two authored examples and connected dynamic diagrams',()=>{assert.equal(p.lessons.filter(x=>x.readiness.visualMatch).length,80);for(const l of p.lessons.slice(70)){assert.equal(l.examples.length,2);assert.equal(l.steps.length,5);}for(const motif of ['bird','sprout'] as const)for(const body of ['round','tall'] as const)for(const mark of ['single','split'] as const)for(const expression of ['neutral','happy','surprised'] as const)for(const pose of ['stand','wave','sit','walk'] as const){const lines=originalLines({motif,body,mark,palette:0},expression,pose);assert.equal(new Set(lines.map(x=>x.id)).size,8);assert.ok(lines.every(x=>!/[<>]/.test(x.d)));}});
test('owner, motif, project and saved nonempty vector source filtering',()=>{const {a,b,base}=chain(),good=make(77,[base]),other=structuredClone(base);other.user_id=crypto.randomUUID();const second=chain().base,blank=structuredClone(base);blank.document.strokes=[];assert.deepEqual(originalCandidates(good,[base,other,second,blank,make(74,[],1)],'D74').map(x=>x.id),[base.id]);assert.equal(originalEligible(b.document),true);assert.equal(originalEligible(a.document),true);});
test('two body candidates remain separate and downstream copies only selected body',()=>{const {b}=chain();b.document.original!.design.body='tall';b.document.original!.panels.tall=[ink('#608cc7')];assert.equal(originalSnapshot(b).frames[0].strokes[0].color,'#608cc7');b.document.original!.panels.round=[];assert.equal(originalEligible(b.document),false);assert.equal(recommend(p,[b])?.lessonId,'D72');});
test('own source snapshots survive original mutation/deletion and roundtrip without touching originals',()=>{const {base}=chain(),next=make(75,[base]),before=structuredClone(base);next.document.strokes[0].points[0][0]=10;assert.deepEqual(base,before);base.document.strokes=[];assert.equal(next.document.original!.sources[0].frames[0].strokes.length,1);assert.deepEqual(parseAttempt(JSON.parse(JSON.stringify(next))),next);assert.equal(originalCandidates(next,[],'D74').length,0);assert.equal(originalEligible(next.document),true);});
test('coloring requires source copy and both chosen palette colors; source line art preserved',()=>{const {base}=chain(),a=make(76,[base]);assert.equal(originalEligible(a.document),false);a.document.original!.copied=true;a.document.strokes.push(...PALETTES[0].map(ink));assert.equal(originalEligible(a.document),true);assert.equal(base.document.strokes.length,1);a.document.original!.design.palette=1;assert.equal(originalEligible(a.document),false);});
test('three expressions and poses, partial save gates, one character card confirms only a full self-check',()=>{const {base}=chain(),emotion=make(77,[base]),expressions=make(78,[base,emotion]);assert.equal(originalEligible(expressions.document),false);expressions.document.original!.expression='surprised';assert.equal(originalEligible(expressions.document),true);const poses=make(79,[base]);poses.document.original!.panels.wave=[ink()];assert.equal(originalEligible(poses.document),false);poses.document.original!.panels.second=[ink()];assert.equal(originalEligible(poses.document),true);const card=make(80,[base,expressions,poses]);card.document.original!.features=['shape','mark'];assert.equal(originalFrames(expressions.document).length,3);assert.equal(originalEligible(card.document),true);assert.equal(confirmedStage(p,[card],9),true);assert.deepEqual(parseAttempt(JSON.parse(JSON.stringify(card))),card);card.document.original!.features=[];assert.equal(confirmedStage(p,[card],9),false);});
test('cross-project, wrong lesson and duplicate source links cannot enter stored document',()=>{const {base}=chain(),a=make(75,[base]);a.document.original!.sources[0].projectId=crypto.randomUUID();assert.throws(()=>parseAttempt(a));a.document.original!.sources[0].projectId=a.document.original!.projectId;a.document.original!.sources[0].lessonId='D79';assert.throws(()=>parseAttempt(a));});
test('paper/external comparison requires explicit note and role, without claiming a vector collection',()=>{const a=make(79);a.document.tool='paper';assert.equal(originalEligible(a.document),false);a.document.original!.note='종이 세 장을 직접 나란히 놓았어요';assert.equal(originalEligible(a.document),true);a.document.character.role='';assert.equal(originalEligible(a.document),false);});
