import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {newDocument,parsePack,parseAttempt,type Attempt,type Stroke} from './model.ts';
import {projectLesson,projectState,projectCandidates,projectSource,projectEdit,projectSavePatch,projectEligible} from './projects.ts';
import {recommend} from './recommend.ts';
const pack=parsePack(JSON.parse(readFileSync(new URL('../../content/drawing/foundations-v1.json',import.meta.url),'utf8')));
const owner=crypto.randomUUID(),ink:Stroke={points:[[100,100,.5],[200,200,.5]],width:2.6,color:'#34314b',erase:false};
function make(id='C01'):Attempt {const l=id.startsWith('C')?projectLesson(pack,id):pack.lessons.find(l=>l.id===id)!;return {id:crypto.randomUUID(),user_id:owner,revision:1,status:'draft',created_at:'2026-09-25',updated_at:'2026-09-25',document:newDocument(l,l.examples[0],pack.version)};}
test('project copies are private, saved vector sources and remain independent of the original',()=>{const a=make(),source=make('D74');source.document.strokes=[structuredClone(ink)];const other=structuredClone(source);other.user_id=crypto.randomUUID();assert.deepEqual(projectCandidates(a,[source,other,{...source,revision:0}]),[source]);a.document.project={...projectState(a.document),source:projectSource(source)};a.document.references=[source.id];source.document.strokes[0].points[0][0]=5;assert.equal(a.document.project.source!.strokes[0].points[0][0],100);assert.deepEqual(parseAttempt(JSON.parse(JSON.stringify(a))),a);a.document.references=[];assert.throws(()=>parseAttempt(a));});
test('four sessions save in order, resume both faces and require comparison',()=>{const a=make(),d=a.document,source=make('D74');source.document.strokes=[ink];d.project={...projectState(d),source:projectSource(source)};d.references=[source.id];assert.throws(()=>projectSavePatch(d));for(let i=0;i<4;i++){d.step=i;d.project.notes[i]='이번 회차의 실제 선택';d.project.boards=[structuredClone([ink]),structuredClone([ink])];if(i===3){assert.throws(()=>projectSavePatch(d));d.project.compared=true;}Object.assign(d,projectSavePatch(d));assert.deepEqual(parseAttempt(JSON.parse(JSON.stringify(a))),a);}assert.equal(projectEligible(d),true);Object.assign(d,projectEdit(d,{notes:[...d.project.notes.slice(0,3),'수정'] as typeof d.project.notes}));assert.equal(projectEligible(d),false);});
test('editing an earlier session invalidates that session and its dependents, without erasing drawings',()=>{const a=make(),d=a.document;d.project={...projectState(d),saved:[true,true,true,true],boards:[[ink],[ink]]};d.step=1;const patch=projectEdit(d,{name:'다시'});assert.deepEqual(patch.project!.saved,[true,false,false,false]);assert.equal(patch.project!.boards[1].length,1);const broken=structuredClone(a);broken.document.project!.saved=[false,true,false,false];assert.throws(()=>parseAttempt(broken));});
test('paper and external sessions require their own notes and never imply app vector evidence',()=>{for(const tool of ['paper','external'] as const){const d=make('C04').document;d.tool=tool;d.project=projectState(d);for(let i=0;i<4;i++){d.step=i;d.project.notes[i]='종이에서 직접 확인';if(i===3){d.project.compared=true;assert.throws(()=>projectSavePatch(d));d.project.name='작은 묶음';}Object.assign(d,projectSavePatch(d));}assert.equal(projectEligible(d),true);assert.equal(d.project.boards.flat().length,0);}});
test('project records do not reset or advance the basic curriculum recommendation',()=>{const base=make('D58'),project=make('C02');project.updated_at='2026-09-26';assert.deepEqual(recommend(pack,[base,project]),recommend(pack,[base]));assert.equal(pack.lessons.length,80);assert.equal(projectLesson(pack,'C03').steps.length,4);});
