'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '../../lib/supabase';
import {useUnsavedChanges} from '@/components/useUnsavedChanges';
type Memory={id:string;user_id:string;topic:string;content:string};
type Change={owner:string;id:string;before:Memory|null;after:{topic:string;content:string}|null};
export default function MemoriesPage(){
 const [rows,setRows]=useState<Memory[]>([]),[owner,setOwner]=useState(''),[loading,setLoading]=useState(true),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 const [editing,setEditing]=useState<Memory|null>(null),[topic,setTopic]=useState('일반'),[content,setContent]=useState(''),[change,setChange]=useState<Change|null>(null),[attempted,setAttempted]=useState(false),[busy,setBusy]=useState(false);const lock=useRef(false);
 useUnsavedChanges(Boolean(content||change));
 const load=useCallback(async()=>{setLoading(true);setReady(false);try{if(!supabase)throw Error();const auth=await supabase.auth.getUser();if(auth.error||!auth.data.user)throw Error();const result=await supabase.from('assistant_memories').select('id,user_id,topic,content').eq('user_id',auth.data.user.id).order('created_at',{ascending:false}).abortSignal(AbortSignal.timeout(15000));if(result.error)throw Error();setOwner(auth.data.user.id);setRows(result.data??[]);setReady(true);}catch{setNotice('기억을 불러오지 못했습니다. 빈 목록으로 판단하지 않습니다. 다시 불러와 주세요.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const reset=()=>{setEditing(null);setTopic('일반');setContent('');setChange(null);setAttempted(false);};
 const review=(before:Memory|null,remove=false)=>{if(!ready)return;const after=remove?null:{topic:topic.trim(),content:content.trim()};if(after&&(!after.topic||after.topic.length>80||!after.content||after.content.length>2000)){setNotice('주제는 1~80자, 기억은 1~2,000자로 입력해 주세요.');return;}setChange({owner,id:before?.id??crypto.randomUUID(),before,after});setAttempted(false);setNotice('');};
 const confirm=async()=>{if(!supabase||!change||lock.current)return;lock.current=true;setBusy(true);setNotice('');try{
  const auth=await supabase.auth.getUser();if(auth.error||auth.data.user?.id!==change.owner)throw Error('로그인 계정이 변경됐습니다. 다시 불러와 주세요.');
  if(!attempted){setAttempted(true);try{let write;if(!change.before){write=supabase.from('assistant_memories').insert({id:change.id,user_id:change.owner,...change.after!});}else{const query=change.after?supabase.from('assistant_memories').update(change.after):supabase.from('assistant_memories').delete();write=query.eq('id',change.id).eq('user_id',change.owner).eq('topic',change.before.topic).eq('content',change.before.content);}await write.abortSignal(AbortSignal.timeout(15000));}catch{/* Confirm the same record before any new write. */}}
  const result=await supabase.from('assistant_memories').select('id,user_id,topic,content').eq('id',change.id).eq('user_id',change.owner).abortSignal(AbortSignal.timeout(15000)).maybeSingle();if(result.error)throw Error('저장 결과를 확인하지 못했습니다. 서버 결과 재확인으로 조회만 다시 시도해 주세요.');
  const matches=change.after?result.data?.topic===change.after.topic&&result.data?.content===change.after.content:result.data===null;
  if(!matches)throw Error('기록이 변경됐거나 반영되지 않았습니다. 덮어쓰지 않습니다. 확인 화면을 닫고 다시 불러와 주세요.');
  const removed=!change.after;reset();await load();setNotice(removed?'확인한 기억을 삭제했습니다.':'확인한 기억을 저장했습니다.');
 }catch(error){setNotice(error instanceof Error?error.message:'기억 변경 결과를 확인하지 못했습니다.');}finally{lock.current=false;setBusy(false);}};
 return <main className="mx-auto min-h-dvh max-w-3xl px-4 py-6 text-gray-900"><Link href="/assistant" className="text-sm font-bold text-violet-700">← AI 연이</Link><h1 className="mt-4 text-2xl font-bold">연이 기억 관리</h1><p className="mt-2 text-sm leading-6 text-gray-500">직접 저장한 기억을 관련 답변에 사용합니다. 기억을 고쳐도 원본 일정·운동·식단 기록은 바뀌지 않습니다.</p>
  <button type="button" disabled={loading||busy||Boolean(change)} onClick={()=>void load()} className="my-3 min-h-11 rounded-xl bg-violet-50 px-4 text-sm font-bold">기억 다시 불러오기</button>
  {notice&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-sm">{notice}</p>}
  <section aria-label="기억 입력" className="my-4 rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-bold">{editing?'기억 수정':'새 기억'}</h2><label className="mt-3 block text-sm">주제<input aria-label="기억 주제" disabled={busy||Boolean(change)} maxLength={80} value={topic} onChange={e=>setTopic(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border p-2"/></label><label className="mt-3 block text-sm">내용<textarea aria-label="기억 내용" disabled={busy||Boolean(change)} maxLength={2000} value={content} onChange={e=>setContent(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border p-2"/></label><div className="mt-3 flex flex-wrap gap-2"><button disabled={!ready||busy||Boolean(change)||!content.trim()} onClick={()=>review(editing)} className="min-h-11 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white disabled:opacity-50">기억 저장 검토</button><button disabled={busy} onClick={reset} className="min-h-11 rounded-xl bg-gray-100 px-4 text-sm">입력 취소</button></div></section>
  {change&&<section aria-label="기억 변경 확인" className="my-4 rounded-2xl bg-amber-50 p-4 text-sm"><h2 className="font-bold">{change.after?'기억 저장 확인':'기억 삭제 확인'}</h2><p className="mt-2 whitespace-pre-wrap break-words">변경 전: {change.before?`${change.before.topic} · ${change.before.content}`:'새 기억'}</p><p className="mt-2 whitespace-pre-wrap break-words">변경 후: {change.after?`${change.after.topic} · ${change.after.content}`:'삭제'}</p>{!change.after&&<p className="mt-2">삭제한 기억은 복구되지 않습니다.</p>}<div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void confirm()} className="min-h-11 rounded-xl bg-violet-700 px-4 font-bold text-white">{busy?'결과 확인 중…':attempted?'기억 서버 결과 재확인':'확인 후 기억 반영'}</button><button disabled={busy} onClick={()=>{setChange(null);setAttempted(false);}} className="min-h-11 rounded-xl bg-white px-4">확인 화면 닫기</button></div></section>}
  <section aria-label="저장된 기억"><h2 className="font-bold">저장된 기억</h2>{loading?<p>기억을 불러오는 중…</p>:!ready?<p>현재 기억을 확인하지 못했습니다.</p>:!rows.length?<p className="py-3 text-sm">저장한 기억이 없습니다.</p>:<ul className="mt-3 space-y-3">{rows.map(row=><li key={row.id} className="rounded-2xl bg-white p-4 shadow-sm"><strong>{row.topic}</strong><p className="mt-2 whitespace-pre-wrap break-words text-sm">{row.content}</p><div className="mt-3 flex gap-2"><button disabled={busy||Boolean(change)} onClick={()=>{setEditing(row);setTopic(row.topic);setContent(row.content);setNotice('');}} className="min-h-11 rounded-xl bg-violet-50 px-4 text-sm">기억 수정</button><button disabled={busy||Boolean(change)} onClick={()=>review(row,true)} className="min-h-11 rounded-xl bg-red-50 px-4 text-sm text-red-700">기억 삭제 검토</button></div></li>)}</ul>}</section>
 </main>;
}
