"use client";
import type {Attempt,DrawingDocument} from '@/lib/drawing/model';
import {identityState,identityLines,identityCandidates,identitySnapshot,identityReferences} from '@/lib/drawing/identity';
import {exportExample} from '@/lib/drawing/export';
import {Diagram} from './Diagram';
import {DrawingCanvas} from './DrawingCanvas';

export function IdentityDiagram({doc,mode}:{doc:DrawingDocument;mode:'baseline'|'target'|'demo'|'easy'}) {
 const meta=doc.example.identity;if(!meta)return null;
 const state=identityState(doc),option=meta.options.find(o=>o.id===state.choice)??meta.options[0];
 const lines=mode==='baseline'?(state.baseline?.lines??meta.baseline):identityLines(doc);
 const ids=mode==='demo'?option.frames[doc.step]:mode==='easy'?meta.features.filter(f=>state.features.includes(f.id)).flatMap(f=>f.lines):null;
 return <svg viewBox="0 0 400 400" role="img" aria-label={mode==='baseline'?'캐릭터 기준':mode==='target'?'선택한 표정과 자세':'특징과 그리는 순서'} className="h-full w-full" data-testid={`identity-${mode}`}>
  {lines.filter(l=>!ids||ids.includes(l.id)).map(l=><path key={l.id} data-line={l.id} d={l.d} fill={l.fill==='ink'?(mode==='easy'?'#7750c4':'#34314b'):'none'} stroke={l.fill==='ink'?'none':mode==='easy'?'#7750c4':'#34314b'} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>)}
 </svg>;
}
export default function IdentityPractice({attempt,records,original,easy,disabled,onChange}:{attempt:Attempt;records:Attempt[];original:boolean;easy:boolean;disabled:boolean;onChange:(patch:Partial<DrawingDocument>)=>void}) {
 const doc=attempt.document,meta=doc.example.identity,state=identityState(doc);if(!meta)return <p role="alert">캐릭터 예제를 열지 못했어요.</p>;
 const collection=doc.lesson.identityPractice!=='draw',bases=identityCandidates(attempt,records,'baseline'),candidates=identityCandidates(attempt,records,'collection');
 const patch=(value:Partial<typeof state>)=>onChange({identity:{...state,...value}});
 const sourceNote='고를 수 있는 그림은 같은 캐릭터로 앱에서 그려 저장한 본인 그림이에요. 종이·다른 앱 그림은 직접 나란히 놓고 비교해요.';
 return <section role="region" aria-label="같은 캐릭터 연습" className="space-y-4">
  <p className="text-sm">표정과 자세는 바꿔도 같은 친구로 보이는 특징 두 개를 남겨요. 내 그림을 자동으로 채점하지 않아요.</p>
  <fieldset disabled={disabled} className="rounded-xl border p-3"><legend className="font-semibold">유지할 특징 두 개</legend>{meta.features.map(f=><label key={f.id} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" aria-label={f.label} checked={state.features.includes(f.id)} disabled={!state.features.includes(f.id)&&state.features.length===2} onChange={e=>patch({features:e.target.checked?[...state.features,f.id]:state.features.filter(x=>x!==f.id),compared:false})}/>{f.label}</label>)}</fieldset>
  {doc.lesson.id!=='D61'&&<div className="rounded-xl bg-slate-50 p-3"><label className="block text-sm">저장한 D61 기준 그림<select className="drawing-input mt-2 w-full" aria-label="저장한 D61 기준 그림" disabled={disabled} value={state.baseline?.attemptId??''} onChange={e=>{const a=bases.find(x=>x.id===e.target.value);const next={...state,baseline:a?identitySnapshot(a):undefined,features:a?.document.identity?.features.length===2?[...a.document.identity.features]:state.features,compared:false};onChange({identity:next,references:identityReferences(next)});}}><option value="">제공된 기준 예제로 연습</option>{bases.map(a=><option key={a.id} value={a.id}>{a.document.example.name} · {new Date(a.updated_at).toLocaleDateString('ko-KR')}</option>)}{state.baseline&&!bases.some(x=>x.id===state.baseline?.attemptId)&&<option value={state.baseline.attemptId}>당시 기준 그림의 보관된 복사본</option>}</select></label><p className="mt-2 text-xs">{sourceNote} 기준 그림을 고르면 당시 특징 두 개와 그림을 함께 보관해요.</p>{original&&state.baseline&&<DrawingCanvas strokes={state.baseline.strokes} preview/>}</div>}
  {meta.options.length>1&&<fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend className="mb-2 text-sm">바꿀 표정 또는 상황</legend>{meta.options.map(o=><button key={o.id} className={o.id===state.choice?'drawing-primary':'drawing-button'} aria-pressed={o.id===state.choice} onClick={()=>patch({choice:o.id,compared:false})}>{o.label}</button>)}</fieldset>}
  {original&&<div className="grid grid-cols-2 gap-3"><div><p className="text-sm font-semibold">기준 예제</p><IdentityDiagram doc={doc} mode="baseline"/></div><div><p className="text-sm font-semibold">{doc.example.name}</p><IdentityDiagram doc={doc} mode="target"/></div></div>}
  {original&&meta.comparison&&<div className="mx-auto max-w-xs"><p className="text-sm">반가운 입과 처진 눈·입의 방향 비교</p><Diagram example={{...doc.example,lines:meta.comparison}} original/></div>}
  {easy&&original&&meta.easyReference&&<div className="mx-auto max-w-xs"><p className="text-sm">더 쉽게: 다리를 생략한 앉은 몸</p><Diagram example={{...doc.example,lines:meta.easyReference}} original/></div>}
  {collection&&doc.tool==='app'&&<div className="rounded-xl border p-3"><h3 className="font-semibold">{doc.lesson.id==='D65'?'저장한 세 표정 모으기':'저장한 자세 두 개 모으기'}</h3><p className="my-2 text-sm">{sourceNote} {doc.lesson.id==='D65'?'D62·D63·D64에서 하나씩 골라요.':'D61 기준과 D66~D69 중 서로 다른 수업 두 개를 골라요.'} 더 쉽게 연습할 때는 일부만 골라도 돼요.</p>{!candidates.length&&<p className="text-sm">아직 고를 그림이 없어요. 앞 수업을 저장한 뒤 돌아오세요. 제공 예제로 일부만 연습할 수도 있어요.</p>}
   {candidates.map(a=><label key={a.id} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" aria-label={`모음 ${a.document.lesson.id} ${a.id}`} checked={state.collection.some(x=>x.attemptId===a.id)} disabled={disabled||(!state.collection.some(x=>x.attemptId===a.id)&&(state.collection.length>=3||state.collection.some(x=>x.lessonId===a.document.lesson.id)))} onChange={e=>{const items=e.target.checked?[...state.collection,identitySnapshot(a)]:state.collection.filter(x=>x.attemptId!==a.id);const next={...state,collection:items,editing:items.some(x=>x.attemptId===state.editing)?state.editing:undefined,compared:false};onChange({identity:next,references:identityReferences(next)});}}/>{a.document.lesson.id} · {a.document.example.name}</label>)}
   <div className="mt-3 grid gap-3 sm:grid-cols-3">{state.collection.map(source=><article className="rounded-xl border p-2" key={source.attemptId}><p className="text-sm font-semibold">{source.label}</p>{original&&<DrawingCanvas strokes={source.strokes} preview/>}{!candidates.some(a=>a.id===source.attemptId&&a.revision===source.revision)&&<p className="text-xs">당시 저장된 복사본이에요. 원본의 이후 변경은 여기 반영하지 않아요.</p>}<button className="drawing-button" aria-pressed={state.editing===source.attemptId} disabled={disabled} onClick={()=>{if(doc.strokes.length&&!window.confirm('지금 연습장의 선을 이 그림의 복사본으로 바꿀까요? 선택한 원본은 그대로 남아요.'))return;onChange({strokes:structuredClone(source.strokes),photo:null,identity:{...state,editing:source.attemptId,compared:false}});}}>이 그림을 복사해 보완</button><button className="drawing-button mt-2" disabled={disabled} onClick={()=>{const next={...state,collection:state.collection.filter(x=>x.attemptId!==source.attemptId),editing:state.editing===source.attemptId?undefined:state.editing,compared:false};onChange({identity:next,references:identityReferences(next)});}}>모음에서 빼기</button></article>)}</div>
  </div>}
  {doc.tool==='app'?<DrawingCanvas key={`${attempt.id}-${state.editing??'new'}`} strokes={doc.strokes} disabled={disabled} guide={easy?<div className="absolute inset-0 opacity-40"><IdentityDiagram doc={doc} mode="easy"/>{meta.anchors&&<svg className="absolute inset-0 h-full w-full" viewBox="0 0 400 400" aria-label="두 발 위치 도움">{meta.anchors.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="5" fill="#bd530c"/>)}</svg>}</div>:undefined} reference={original?<IdentityDiagram doc={doc} mode="target"/>:undefined} onChange={strokes=>onChange({strokes,identity:{...state,compared:false}})}/>:<p className="rounded-xl bg-violet-50 p-3 text-sm">{collection?'종이 그림이나 다른 앱의 저장한 그림을 나란히 놓아요. 원본을 복사한 뒤 한 곳만 보완해요. 모음 사진을 아래에서 넣거나 비교 메모만 저장해도 돼요.':'종이 또는 다른 앱에서 기준 특징 두 개를 표시하고 그려요. 예제를 내려받아 옆에 놓아도 돼요.'}</p>}
  {!collection&&<details className="rounded-xl bg-slate-50 p-3" onToggle={e=>{if(e.currentTarget.open&&doc.usedHelp<3)onChange({usedHelp:3});}}><summary className="cursor-pointer font-semibold">특징을 유지하며 그리는 시범</summary><div className="mx-auto max-w-sm"><IdentityDiagram doc={doc} mode="demo"/></div></details>}
  {collection&&<p className="text-sm">보완한 연습장과 선택한 그림 모음은 함께 저장돼요. 선택한 원본 기록은 바꾸지 않아요. PNG는 현재 보완 그림을 내보내고, 모음 전체는 편집 JSON에 함께 보관해요.</p>}
  <button className="drawing-button" onClick={()=>exportExample({...doc.example,lines:identityLines(doc)})}>선택한 캐릭터 예제 내려받기</button>
  <label className="block text-sm">{doc.lesson.id==='D69'?'어떤 상황인가요?':collection?'유지한 특징과 보완한 한 곳':'비교 메모 · 선택'}<textarea aria-label="캐릭터 비교 메모" className="drawing-input mt-2 w-full" disabled={disabled} maxLength={500} value={state.note} onChange={e=>patch({note:e.target.value})}/></label>
  <label className="flex min-h-11 items-center gap-2 rounded-xl border p-3 text-sm"><input aria-label="캐릭터 특징 비교 완료" type="checkbox" disabled={disabled||doc.step!==doc.lesson.steps.length-1||state.features.length!==2} checked={state.compared} onChange={e=>patch({compared:e.target.checked})}/>마지막 행동에서 두 특징과 바뀐 표정·자세를 비교했어요.</label>
 </section>;
}
