"use client";
import type {Attempt,DrawingDocument,OriginalState,OriginalDesign,OriginalFrame} from '@/lib/drawing/model';
import {originalState,originalCandidates,originalSnapshot,ORIGINAL_SOURCES,PALETTES} from '@/lib/drawing/original';
import {originalLines,ORIGINAL_LABELS} from '@/lib/drawing/original-guide';
import {download,exportExample} from '@/lib/drawing/export';
import {DrawingCanvas,paintStrokes} from './DrawingCanvas';

export function OriginalDiagram({design,expression='neutral',pose='stand',step=4,easy=false,colored=false,colorStep=4}:{design:OriginalDesign;expression?:OriginalFrame['expression'];pose?:OriginalFrame['pose'];step?:number;easy?:boolean;colored?:boolean;colorStep?:number}){
 const lines=originalLines(design,expression,pose),visible=step===0?lines:step===1?lines.slice(0,1):step===2?lines.slice(0,2):step===3?lines.slice(0,5):lines;
 return <svg viewBox="0 0 400 400" role="img" aria-label="선택한 캐릭터 그리기 도해" className="h-full w-full" data-testid="original-guide">{(easy?lines.slice(0,2):visible).map(l=><path key={l.id} data-line={l.id} d={l.d} stroke="#34314b" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" fill={l.fill==='ink'?'#34314b':colored&&((l.id==='body'&&colorStep>=2)||(l.id==='mark'&&colorStep>=3))?PALETTES[design.palette][l.id==='body'?0:1]:'none'}/>)}</svg>;
}
export function OriginalCard({attempt}:{attempt:Attempt}){const s=originalState(attempt),c=attempt.document.character;return <article aria-label="내 캐릭터 소개 카드" className="rounded-2xl border bg-white p-4"><h3 className="break-words text-xl font-bold">{c.name||'이름을 붙여 주세요'}</h3><p className="break-words text-sm">{c.role||'역할'} · {c.personality||'성격'}</p><p className="my-2 break-words text-sm">유지할 특징: {s.features.map(x=>({shape:'큰 몸 비율',mark:'대표 장식',eyes:'눈 사이 간격'})[x]).join(' · ')||'두 개를 골라 주세요'}</p>{[['D74','기준 그림'],['D78','표정 모음'],['D79','자세 모음']].map(([id,label])=><section key={id}><h4 className="mt-3 font-semibold">{label}</h4><div className="grid grid-cols-3 gap-2">{s.sources.find(x=>x.lessonId===id)?.frames.map((f,i)=><div key={i}><DrawingCanvas strokes={f.strokes} preview/><p className="text-xs">{f.label}</p></div>)??<p className="col-span-3 text-sm">아직 고르지 않았어요. 일부만 저장하고 이어 완성해도 돼요.</p>}</div></section>)}<p className="mt-4 break-words text-sm">다음에 바꿔볼 것: {c.improvement||'한 곳을 골라 주세요'}</p><p className="mt-2 text-xs">입문 창작 기록 · 자기확인. 모든 화풍·전문 제작 과정을 마쳤다는 뜻은 아니에요.</p></article>;}
function exportCard(a:Attempt){const s=originalState(a),c=a.document.character,canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1550;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='white';ctx.fillRect(0,0,1000,1550);ctx.fillStyle='#34314b';ctx.font='bold 36px sans-serif';ctx.fillText(c.name||'내 캐릭터',40,60,920);ctx.font='24px sans-serif';ctx.fillText(`${c.role} · ${c.personality}`,40,102,920);ctx.fillText(`특징: ${s.features.map(x=>({shape:'몸 비율',mark:'대표 장식',eyes:'눈 간격'})[x]).join(', ')}`,40,143,920);
 for(const [row,id] of ['D74','D78','D79'].entries()){const y=190+row*400;ctx.font='bold 26px sans-serif';ctx.fillText(['기준 그림','표정 모음','자세 모음'][row],40,y);const frames=s.sources.find(x=>x.lessonId===id)?.frames??[];frames.forEach((f,i)=>{const tile=document.createElement('canvas');tile.width=400;tile.height=400;paintStrokes(tile,f.strokes);ctx.drawImage(tile,40+i*310,y+20,290,290);ctx.font='22px sans-serif';ctx.fillText(f.label,45+i*310,y+340,285);});}ctx.font='23px sans-serif';ctx.fillText(`다음에 바꿀 것: ${c.improvement}`,40,1440,920);ctx.font='20px sans-serif';ctx.fillText('입문 창작 기록 · 긴 소개 문장은 편집 JSON에 함께 보관됩니다.',40,1495,920);canvas.toBlob(b=>{if(b)download(b,'D80-character-card.png');});}
export default function OriginalPractice({attempt,records,original,easy,disabled,onChange}:{attempt:Attempt;records:Attempt[];original:boolean;easy:boolean;disabled:boolean;onChange:(p:Partial<DrawingDocument>)=>void}){
 const d=attempt.document,s=originalState(attempt),id=d.lesson.id,multi=id==='D72'||id==='D79',card=id==='D80';
 const patch=(p:Partial<OriginalState>,extra:Partial<DrawingDocument>={})=>onChange({...extra,original:{...s,...p}});
 const design={...s.design,...(id==='D72'?{body:s.active==='tall'?'tall' as const:'round' as const}:{})};
 const expression:OriginalFrame['expression']=['D77','D78'].includes(id)?s.expression:'neutral',pose:OriginalFrame['pose']=id==='D79'?(s.active==='wave'?'wave':s.pose):'stand';
 const diagram=<OriginalDiagram design={design} expression={expression} pose={pose} colored={id==='D76'}/>;
 const selectSource=(lessonId:string,value:string)=>{const found=records.find(x=>x.id===value);if(!found){const next=s.sources.filter(x=>x.lessonId!==lessonId);patch({sources:next,compared:false,copied:false},{references:next.map(x=>x.attemptId)});return;}
  if(!originalCandidates(attempt,records,lessonId).some(x=>x.id===value))return;
  const first=!s.sources.length;if(first&&(d.strokes.length||Object.values(s.panels).some(x=>x.length))&&!window.confirm('저장한 캐릭터를 이어 만들기 위해 지금 연습장의 선을 비울까요? 원본 기록은 유지돼요.'))return;
  const source=originalSnapshot(found),sources=[...s.sources.filter(x=>x.lessonId!==lessonId),source].sort((a,b)=>a.lessonId.localeCompare(b.lessonId));
  patch({sources,projectId:source.projectId,...(first?{design:source.design,panels:{round:[],tall:[],wave:[],second:[]}}:{}),...(id==='D78'&&lessonId==='D77'?{expression:source.frames[0].expression==='happy'?'surprised':'happy'}:{}),compared:false,copied:false},{references:sources.map(x=>x.attemptId),...(first?{strokes:[],character:{...source.character,name:d.character.name||source.character.name}}:{})});};
 const charField=(key:keyof DrawingDocument['character'],label:string)=><label className="block text-sm">{label}<input aria-label={label} maxLength={300} className="drawing-input mt-1 w-full" disabled={disabled} value={d.character[key]} onChange={e=>patch({compared:false},{character:{...d.character,[key]:e.target.value}})}/></label>;
 return <section role="region" aria-label="나만의 캐릭터 제작" className="space-y-4">
  <p className="text-sm">작은 {s.design.motif==='sprout'?'새싹':'새'}를 출발점으로 내 역할·모양·특징을 정해요. 예제는 방법을 보여주는 도해이고, 결과물은 연습장에 직접 그린 내 그림이에요.</p>
  {id==='D71'&&<div className="flex flex-wrap gap-2">{['앱에서 반겨주는 친구','작은 모험가'].map(x=><button key={x} className="drawing-button" disabled={disabled} onClick={()=>patch({compared:false},{character:{...d.character,role:x}})}>{x}</button>)}{['다정함','호기심'].map(x=><button key={x} className="drawing-button" disabled={disabled} onClick={()=>patch({compared:false},{character:{...d.character,personality:x}})}>{x}</button>)}</div>}
  {charField('role','캐릭터 역할')}{charField('personality','캐릭터 성격')}
  {ORIGINAL_SOURCES[id].length>0&&d.tool==='app'&&<fieldset disabled={disabled} className="space-y-3 rounded-xl border p-3"><legend className="font-semibold">내 캐릭터 이어 만들기</legend><p className="text-sm">같은 모티프의 본인 저장 그림을 골라요. 첫 원본을 고르면 그 캐릭터의 다음 그림만 보여요. 원본은 보관하고 당시 복사본을 이 수업에 함께 저장해요.</p>{ORIGINAL_SOURCES[id].map(lessonId=>{const list=originalCandidates(attempt,records,lessonId),chosen=s.sources.find(x=>x.lessonId===lessonId);return <label key={lessonId} className="block text-sm">{lessonId} 원본<select aria-label={`${lessonId} 원본`} className="drawing-input mt-1 w-full" value={chosen?.attemptId??''} onChange={e=>selectSource(lessonId,e.target.value)}><option value="">원본을 골라 주세요</option>{list.map(a=><option value={a.id} key={a.id}>{a.document.character.name||a.document.example.name} · {new Date(a.updated_at).toLocaleDateString('ko-KR')}</option>)}{chosen&&!list.some(a=>a.id===chosen.attemptId)&&<option value={chosen.attemptId}>당시 보관한 원본 복사본</option>}</select>{!list.length&&!chosen&&<span>앞 수업을 먼저 저장하거나, 예제로 일부만 연습해요.</span>}</label>;})}</fieldset>}
  {!card&&original&&s.sources.length>0&&<div className="grid grid-cols-2 gap-3">{s.sources.flatMap(source=>source.frames.map((f,i)=><article className="rounded-xl border p-2" key={`${source.attemptId}-${i}`}><p className="text-sm">내 {source.lessonId} · {f.label}</p><DrawingCanvas strokes={f.strokes} preview/><p className="text-xs">당시 저장된 복사본 · 원본의 이후 변경·삭제와 별도로 유지돼요.</p></article>))}</div>}
  {id==='D72'&&<><fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend>두 후보를 각각 그려요</legend>{(['round','tall'] as const).map(key=><button key={key} aria-pressed={s.active===key} className="drawing-button" onClick={()=>patch({active:key,compared:false},{strokes:s.panels[key]})}>{key==='round'?'둥근 후보':'길쭉한 후보'}</button>)}</fieldset><label className="block text-sm">이어 만들 몸<select aria-label="이어 만들 몸" className="drawing-input w-full" disabled={disabled} value={s.design.body} onChange={e=>patch({design:{...s.design,body:e.target.value as 'round'|'tall'},compared:false})}><option value="round">둥근 몸</option><option value="tall">길쭉한 몸</option></select></label><label className="block text-sm">고른 이유<input aria-label="고른 이유" className="drawing-input w-full" maxLength={500} disabled={disabled} value={s.reason} onChange={e=>patch({reason:e.target.value,compared:false})}/></label><button className="drawing-button" disabled={disabled} onClick={()=>patch({reason:s.design.body==='round'?'더 포근해 보여요':'더 가볍고 활발해 보여요',compared:false})}>선택 이유 예시 넣기</button></>}
  {id==='D73'&&<fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend>대표 특징 하나</legend>{(['single','split'] as const).map(mark=><button className="drawing-button" aria-pressed={s.design.mark===mark} key={mark} onClick={()=>patch({design:{...s.design,mark},compared:false})}>{mark==='single'?'한 줄기 특징':'갈라진 특징'}</button>)}</fieldset>}
  {id==='D76'&&<><fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend>주색과 보조색</legend>{PALETTES.map((colors,i)=><button className="drawing-button" key={i} aria-pressed={s.design.palette===i} onClick={()=>patch({design:{...s.design,palette:i},compared:false})}>색 조합 {i+1} {colors.map(c=><span key={c} style={{background:c}} className="ml-1 inline-block h-4 w-4 rounded-full"/>)}</button>)}</fieldset><button disabled={disabled||!s.sources.length} className="drawing-button" onClick={()=>{if(d.strokes.length&&!window.confirm('현재 연습장을 원본 선화의 복사본으로 바꿀까요?'))return;patch({copied:true,compared:false},{strokes:structuredClone(s.sources[0].frames[0].strokes),photo:null});}}>내 선화 복사해서 색 넣기</button><p className="text-sm">넓은 부분은 주색, 대표 특징은 보조색으로 칠해요. 원본 선화는 그대로 남아요. 종이에서는 연필의 연함·진함으로 대신해도 돼요.</p></>}
  {['D77','D78'].includes(id)&&<fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend>{id==='D78'?'모음에 없는 세 번째 표정':'첫 표정 고르기'}</legend>{(['happy','surprised'] as const).map(expression=><button key={expression} className="drawing-button" aria-pressed={s.expression===expression} onClick={()=>patch({expression,compared:false})}>{ORIGINAL_LABELS[expression]}</button>)}</fieldset>}
  {id==='D79'&&<><fieldset disabled={disabled} className="flex flex-wrap gap-2"><legend>오늘 그릴 자세</legend>{(['wave','second'] as const).map(active=><button key={active} className="drawing-button" aria-pressed={s.active===active} onClick={()=>patch({active,compared:false},{strokes:s.panels[active]})}>{active==='wave'?'인사 연습장':'두 번째 자세 연습장'}</button>)}</fieldset><label className="block text-sm">두 번째 자세<select aria-label="두 번째 자세" disabled={disabled} className="drawing-input w-full" value={s.pose} onChange={e=>{if(s.panels.second.length&&!window.confirm('자세를 바꾸면 두 번째 연습장의 선을 비워요. 바꿀까요?'))return;patch({pose:e.target.value as 'sit'|'walk',panels:{...s.panels,second:[]},compared:false},s.active==='second'?{strokes:[]}:{});}}><option value="sit">앉기</option><option value="walk">걷기</option></select></label><p className="text-sm">두 연습장은 각각 저장돼요. 오늘 인사 한 장을 그리고 ‘잠깐 쉬기 · 저장’으로 다음에 이어 그려도 돼요.</p></>}
  {card?<>{charField('name','캐릭터 이름')}{charField('improvement','다음에 바꿀 것')}<fieldset disabled={disabled}><legend>소개 카드에 유지할 특징 두 개</legend>{(['shape','mark','eyes'] as const).map(key=><label key={key} className="flex min-h-11 items-center gap-2"><input type="checkbox" aria-label={`카드 특징 ${key}`} checked={s.features.includes(key)} disabled={!s.features.includes(key)&&s.features.length===2} onChange={e=>patch({features:e.target.checked?[...s.features,key]:s.features.filter(x=>x!==key),compared:false})}/>{{shape:'큰 몸 비율',mark:'대표 장식',eyes:'눈 사이 간격'}[key]}</label>)}</fieldset><OriginalCard attempt={attempt}/><button className="drawing-button" disabled={disabled||!s.sources.length} onClick={()=>exportCard(attempt)}>소개 카드 PNG 내려받기</button><p className="text-sm">이름·역할·메모와 모든 원본 복사본은 저장·편집 JSON에 보관돼요. PNG는 그림 모음과 짧은 소개를 담아요.</p></>:<>
   {original&&<div className="mx-auto max-w-sm"><p className="text-sm font-semibold">선택한 모양의 방법 예제</p>{diagram}</div>}
   {d.tool==='app'?<DrawingCanvas key={`${attempt.id}-${multi?s.active:'main'}-${s.copied}`} strokes={multi?s.panels[s.active]:d.strokes} disabled={disabled} palette={id==='D76'?PALETTES[s.design.palette]:undefined} guide={easy?<div className="absolute inset-0 opacity-40"><OriginalDiagram design={design} expression={expression} pose={pose} easy/></div>:undefined} onChange={strokes=>patch({compared:false,...(multi?{panels:{...s.panels,[s.active]:strokes}}:{})},{strokes})}/>:<p className="rounded-xl bg-violet-50 p-3 text-sm">종이·다른 앱에서는 원본을 직접 나란히 놓고 복사해 연습해요. 그림 모음은 사진으로 보관하고, 비교 메모에 어떤 그림을 모았는지 적어요. 앱에서 그린 모음과 구분된 자기확인으로 저장돼요.</p>}
   <details className="rounded-xl bg-slate-50 p-3" onToggle={e=>{if(e.currentTarget.open&&d.usedHelp<3)onChange({usedHelp:3});}}><summary className="cursor-pointer font-semibold">큰 모양부터 그리는 시범</summary><OriginalDiagram design={design} expression={expression} pose={pose} step={id==='D76'?4:d.step} colored={id==='D76'} colorStep={d.step}/></details>
   <button className="drawing-button" onClick={()=>exportExample({...d.example,lines:originalLines(design,expression,pose)})}>선택한 창작 예제 내려받기</button>
  </>}
  {original&&['D73','D76'].includes(id)&&<div className="flex items-center gap-3 rounded-xl border p-3"><div className="h-16 w-16 shrink-0">{diagram}</div><p className="text-sm">작은 앱 아이콘 크기에서도 대표 특징이 보이나요?</p></div>}
  {multi&&<p className="text-sm">두 연습장은 함께 저장돼요. 일반 PNG는 현재 연습장만 담고, 전체 그림은 편집 JSON에 함께 담아요.</p>}
  {card&&d.tool!=='app'&&<p className="text-sm">종이·다른 앱 모음은 아래 사진 첨부와 메모로 보관해요. 앱 그림을 고르지 않은 빈 카드 대신 실제 모음 사진을 확인해 주세요.</p>}
  <label className="block text-sm">창작 비교 메모<textarea aria-label="창작 비교 메모" className="drawing-input mt-1 w-full" maxLength={500} disabled={disabled} value={s.note} onChange={e=>patch({note:e.target.value,compared:false})}/></label>
  <label className="flex min-h-11 items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" aria-label="내 캐릭터 비교 완료" disabled={disabled||d.step!==4} checked={s.compared} onChange={e=>patch({compared:e.target.checked})}/>{d.lesson.check} 직접 비교했어요.</label>
 </section>;
}
